# -*- coding: utf-8 -*-
# 生成 176 个金融风控指标（TS 字面量），与现有 24 个合并为 200 个指标库
# 条目：(id, name, group, ds, agg, unit, precision, enabled, desc, vizType?)
#   derived 指标: (id, name, group, ds, agg=None, ..., formula)

EXTRA = [
    # ---------- 客群画像 (16) ----------
    ("m_age_avg", "客户平均年龄", "客群", "ds_customer", "avg", "岁", 0, True, "在贷客户平均年龄"),
    ("m_age_dist", "客户年龄分布", "客群", "ds_customer", "distinct", "人", 0, True, "按年龄分组客户数", "bar"),
    ("m_gender_cnt", "男性客户数", "客群", "ds_customer", "count", "人", 0, True, "性别=男的在贷客户数", "hbar"),
    ("m_married_cnt", "已婚客户数", "客群", "ds_customer", "count", "人", 0, True, "婚姻状态=已婚的客户数"),
    ("m_edu_cnt", "本科及以上客户数", "客群", "ds_customer", "count", "人", 0, True, "学历=本科/硕士/博士客户数"),
    ("m_house_cnt", "有房客户数", "客群", "ds_customer", "count", "人", 0, True, "住房性质=自有客户数"),
    ("m_car_cnt", "有车客户数", "客群", "ds_customer", "count", "人", 0, True, "拥有车辆的客户数"),
    ("m_work_years_avg", "平均工作年限", "客群", "ds_customer", "avg", "年", 1, True, "在贷客户平均工作年限"),
    ("m_income_avg", "客户平均月收入", "客群", "ds_customer", "avg", "元", 0, True, "客户平均月收入"),
    ("m_income_high_cnt", "高收入客户数", "客群", "ds_customer", "count", "人", 0, True, "月收入≥3万的客户数"),
    ("m_social_cnt", "缴纳社保客户数", "客群", "ds_customer", "count", "人", 0, True, "有社保记录的客户数"),
    ("m_fund_cnt", "缴纳公积金客户数", "客群", "ds_customer", "count", "人", 0, True, "有公积金记录的客户数"),
    ("m_company_avg", "平均企业规模", "客群", "ds_customer", "avg", "人", 0, True, "客户所在企业平均人数"),
    ("m_industry_cnt", "行业分布客户数", "客群", "ds_customer", "distinct", "人", 0, True, "按行业分组的客户数", "bar"),
    ("m_city_cnt", "城市分布客户数", "客群", "ds_customer", "distinct", "人", 0, True, "按城市分组的客户数", "bar"),
    ("m_blacklist_cnt", "黑名单客户数", "客群", "ds_api_demo", "count", "人", 0, True, "命中外部黑名单的在贷客户数"),
    # ---------- 授信额度 (20) ----------
    ("m_credit_line", "授信额度", "授信", "ds_customer", "sum", "元", 0, True, "当前授信额度总额"),
    ("m_credit_remain", "剩余授信额度", "授信", "ds_customer", "sum", "元", 0, True, "授信额度-已用额度"),
    ("m_util_rate", "额度使用率", "授信", "ds_loan", "avg", "%", 2, True, "已用额度/授信额度×100"),
    ("m_util_high_cnt", "额度使用率>90%客户数", "授信", "ds_loan", "count", "人", 0, True, "额度使用率超过90%的客户"),
    ("m_temp_credit", "临时授信额度", "授信", "ds_customer", "sum", "元", 0, True, "临时提额额度总额"),
    ("m_cycle_credit", "循环授信额度", "授信", "ds_customer", "sum", "元", 0, True, "循环额度总额"),
    ("m_upgrade_cnt", "提额次数", "授信", "ds_customer", "sum", "次", 0, True, "近12个月提额次数"),
    ("m_downgrade_cnt", "降额次数", "授信", "ds_customer", "sum", "次", 0, True, "近12个月降额次数"),
    ("m_freeze_amt", "冻结授信额度", "授信", "ds_customer", "sum", "元", 0, True, "被冻结的授信额度"),
    ("m_avail_credit", "可用授信额度", "授信", "ds_customer", "sum", "元", 0, True, "当前可用的授信额度"),
    ("m_credit_avg", "人均授信额度", "授信", "ds_customer", "avg", "元", 0, True, "授信额度/客户数"),
    ("m_credit_peak", "授信使用峰值", "授信", "ds_loan", "max", "元", 0, True, "历史授信使用峰值"),
    ("m_credit_recover", "额度回收金额", "授信", "ds_loan", "sum", "元", 0, True, "逾期后回收的授信额度"),
    ("m_credit_review", "额度复议次数", "授信", "ds_customer", "sum", "次", 0, True, "额度复议申请次数"),
    ("m_guarantee_credit", "担保授信额度", "授信", "ds_loan", "sum", "元", 0, True, "担保类授信总额"),
    ("m_pledge_credit", "质押授信额度", "授信", "ds_loan", "sum", "元", 0, True, "质押类授信总额"),
    ("m_instal_credit", "分期授信额度", "授信", "ds_loan", "sum", "元", 0, True, "分期类授信总额"),
    ("m_cash_credit", "取现授信额度", "授信", "ds_loan", "sum", "元", 0, True, "可取现的授信额度"),
    ("m_credit_expire", "即将到期授信", "授信", "ds_customer", "sum", "元", 0, True, "30天内到期的授信额度"),
    ("m_credit_gap", "授信缺口", "授信", "ds_loan", "sum", "元", 0, True, "客户用信需求与授信差额"),
    # ---------- 贷款账户 (24) ----------
    ("m_loan_balance", "在贷余额", "贷款", "ds_loan", "sum", "元", 0, True, "全部贷款未还本金余额"),
    ("m_loan_cnt", "贷款笔数", "贷款", "ds_loan", "count", "笔", 0, True, "当前在贷贷款笔数"),
    ("m_loan_total", "贷款发放总额", "贷款", "ds_loan", "sum", "元", 0, True, "历史累计发放贷款金额"),
    ("m_loan_principal", "剩余本金", "贷款", "ds_loan", "sum", "元", 0, True, "贷款未还本金合计"),
    ("m_loan_interest", "应收利息", "贷款", "ds_loan", "sum", "元", 0, True, "已计提未收利息"),
    ("m_loan_rate_avg", "平均贷款利率", "贷款", "ds_loan", "avg", "%", 2, True, "在贷贷款加权平均利率"),
    ("m_loan_term_avg", "平均贷款期限", "贷款", "ds_loan", "avg", "月", 0, True, "贷款平均期限（月）"),
    ("m_loan_remain_term", "剩余期数", "贷款", "ds_loan", "sum", "期", 0, True, "全部贷款剩余还款期数"),
    ("m_loan_paid_term", "已还期数", "贷款", "ds_loan", "sum", "期", 0, True, "累计已还期数"),
    ("m_monthly_pay", "月供合计", "贷款", "ds_loan", "sum", "元", 0, True, "客户月还款额合计"),
    ("m_loan_prepay", "提前还款金额", "贷款", "ds_loan", "sum", "元", 0, True, "提前还款金额合计"),
    ("m_loan_prepay_cnt", "提前还款次数", "贷款", "ds_loan", "count", "次", 0, True, "提前还款笔数"),
    ("m_loan_extend", "展期贷款金额", "贷款", "ds_loan", "sum", "元", 0, True, "展期贷款余额"),
    ("m_loan_renew", "借新还旧金额", "贷款", "ds_loan", "sum", "元", 0, True, "借新还旧涉及金额"),
    ("m_loan_new_cnt", "当月新增贷款笔数", "贷款", "ds_loan", "count", "笔", 0, True, "本月新发放贷款笔数"),
    ("m_loan_mature", "当月到期贷款", "贷款", "ds_loan", "sum", "元", 0, True, "当月到期应还本金"),
    ("m_loan_fine", "罚息金额", "贷款", "ds_loan", "sum", "元", 0, True, "逾期罚息合计"),
    ("m_loan_compound", "复利金额", "贷款", "ds_loan", "sum", "元", 0, True, "复利计提金额"),
    ("m_loan_latefee", "滞纳金金额", "贷款", "ds_loan", "sum", "元", 0, True, "滞纳金合计"),
    ("m_loan_status_dist", "贷款状态分布", "贷款", "ds_loan", "distinct", "笔", 0, True, "按贷款状态分组笔数", "pie"),
    ("m_loan_product_dist", "产品分布", "贷款", "ds_loan", "distinct", "元", 0, True, "按产品分组的贷款余额", "pie"),
    ("m_loan_stage5", "五级分类分布", "贷款", "ds_loan", "distinct", "元", 0, True, "正常/关注/次级/可疑/损失分布", "bar"),
    ("m_loan_disbursed", "本月放款金额", "贷款", "ds_loan", "sum", "元", 0, True, "本月实际放款金额"),
    ("m_loan_due_amt", "本月应还金额", "贷款", "ds_loan", "sum", "元", 0, True, "本月全部应还本息"),
    # ---------- 风险逾期 (28) ----------
    ("m_overdue_rate", "逾期率", "风险", "ds_loan", "avg", "%", 2, True, "逾期金额/在贷余额×100"),
    ("m_overdue_amt", "逾期金额", "风险", "ds_loan", "sum", "元", 0, True, "逾期未还金额合计"),
    ("m_overdue_days", "平均逾期天数", "风险", "ds_loan", "avg", "天", 0, True, "逾期客户平均逾期天数"),
    ("m_overdue_cnt", "逾期客户数", "风险", "ds_loan", "count", "人", 0, True, "存在逾期记录的客户数"),
    ("m_m1_amt", "M1逾期金额", "风险", "ds_loan", "sum", "元", 0, True, "逾期1-30天金额"),
    ("m_m2_amt", "M2逾期金额", "风险", "ds_loan", "sum", "元", 0, True, "逾期31-60天金额"),
    ("m_m3_amt", "M3逾期金额", "风险", "ds_loan", "sum", "元", 0, True, "逾期61-90天金额"),
    ("m_m4p_amt", "M4+逾期金额", "风险", "ds_loan", "sum", "元", 0, True, "逾期90天以上金额"),
    ("m_npl_rate", "不良率", "风险", "ds_loan", "avg", "%", 2, True, "不良金额/在贷余额×100"),
    ("m_npl_amt", "不良金额", "风险", "ds_loan", "sum", "元", 0, True, "次级/可疑/损失类贷款金额"),
    ("m_risk_level_dist", "风险等级分布", "风险", "ds_customer", "distinct", "人", 0, True, "低/中/高风险客户分布", "pie"),
    ("m_high_risk_cnt", "高风险客户数", "风险", "ds_customer", "count", "人", 0, True, "风险等级=高的客户数"),
    ("m_score_avg", "行为均分", "风险", "ds_behavior", "avg", "分", 0, True, "客户行为评分均值"),
    ("m_score_low_cnt", "低行为分客户数", "风险", "ds_behavior", "count", "人", 0, True, "行为分低于40的客户数"),
    ("m_anti_fraud_score", "反欺诈均分", "风险", "ds_api_demo", "avg", "分", 0, True, "反欺诈评分均值"),
    ("m_credit_score", "信用均分", "风险", "ds_api_demo", "avg", "分", 0, True, "外部信用评分均值"),
    ("m_dti_ratio", "收入负债比", "风险", "ds_loan", "avg", "%", 2, True, "月负债/月收入×100"),
    ("m_inq_cnt", "征信查询次数", "风险", "ds_api_demo", "sum", "次", 0, True, "近6个月征信硬查询次数"),
    ("m_inq_high_cnt", "查询频繁客户数", "风险", "ds_api_demo", "count", "人", 0, True, "近6个月查询≥10次客户"),
    ("m_rule_hit_cnt", "命中规则数", "风险", "ds_alert", "sum", "次", 0, True, "预警规则命中次数"),
    ("m_alert_cnt", "预警总数", "风险", "ds_alert", "count", "条", 0, True, "当前预警记录数"),
    ("m_red_cnt", "红灯预警数", "风险", "ds_alert", "count", "条", 0, True, "红灯级别预警数"),
    ("m_yellow_cnt", "黄灯预警数", "风险", "ds_alert", "count", "条", 0, True, "黄灯级别预警数"),
    ("m_opp_cnt", "机会预警数", "风险", "ds_alert", "count", "条", 0, True, "机会（营销）级别预警数"),
    ("m_multi_debt_cnt", "多头借贷客户数", "风险", "ds_api_demo", "count", "人", 0, True, "近30天申贷≥3家客户数"),
    ("m_court_cnt", "涉诉客户数", "风险", "ds_api_demo", "count", "人", 0, True, "有法律诉讼记录的客户数"),
    ("m_lost_debt_cnt", "失信客户数", "风险", "ds_api_demo", "count", "人", 0, True, "失信被执行客户数"),
    ("m_relate_risk", "关联风险客户数", "风险", "ds_sql_demo", "count", "人", 0, True, "关联企业/担保圈风险客户"),
    # ---------- 交易行为 (24) ----------
    ("m_txn_amt", "交易金额", "行为", "ds_behavior", "sum", "元", 0, True, "交易金额合计"),
    ("m_txn_cnt", "交易笔数", "行为", "ds_behavior", "count", "笔", 0, True, "交易笔数合计"),
    ("m_txn_daily_avg", "日均交易金额", "行为", "ds_behavior", "avg", "元", 0, True, "每日平均交易金额"),
    ("m_txn_month_avg", "月均消费金额", "行为", "ds_behavior", "avg", "元", 0, True, "每月平均消费金额"),
    ("m_txn_large_cnt", "大额交易笔数", "行为", "ds_behavior", "count", "笔", 0, True, "单笔≥5万交易笔数"),
    ("m_txn_abnormal", "异常交易笔数", "行为", "ds_behavior", "count", "笔", 0, True, "风控规则标记的异常交易"),
    ("m_login_cnt", "登录次数", "行为", "ds_behavior", "sum", "次", 0, True, "累计登录次数"),
    ("m_login_dev_cnt", "登录设备数", "行为", "ds_behavior", "distinct", "台", 0, True, "登录设备去重数"),
    ("m_active_days", "平均活跃天数", "行为", "ds_behavior", "avg", "天", 1, True, "月均活跃天数"),
    ("m_active_ratio", "活跃率", "行为", "ds_behavior", "avg", "%", 2, True, "活跃客户占比"),
    ("m_txn_type_dist", "消费类型分布", "行为", "ds_behavior", "distinct", "元", 0, True, "按消费类型分组金额", "pie"),
    ("m_online_amt", "线上消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "线上渠道消费金额"),
    ("m_offline_amt", "线下消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "线下渠道消费金额"),
    ("m_transfer_amt", "转账金额", "行为", "ds_behavior", "sum", "元", 0, True, "转账支出金额"),
    ("m_transfer_cnt", "转账笔数", "行为", "ds_behavior", "count", "笔", 0, True, "转账笔数"),
    ("m_receive_amt", "收款金额", "行为", "ds_behavior", "sum", "元", 0, True, "收款入账金额"),
    ("m_receive_cnt", "收款笔数", "行为", "ds_behavior", "count", "笔", 0, True, "收款笔数"),
    ("m_game_amt", "游戏充值金额", "行为", "ds_behavior", "sum", "元", 0, True, "游戏类充值金额"),
    ("m_dining_amt", "餐饮消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "餐饮类消费金额"),
    ("m_shopping_amt", "网购消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "电商类消费金额"),
    ("m_travel_amt", "出行消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "出行类消费金额"),
    ("m_pay_fail_cnt", "支付失败笔数", "行为", "ds_behavior", "count", "笔", 0, True, "支付失败交易笔数"),
    ("m_refund_amt", "退款金额", "行为", "ds_behavior", "sum", "元", 0, True, "退款金额合计"),
    ("m_withdraw_cnt", "提现次数", "行为", "ds_behavior", "count", "次", 0, True, "提现次数"),
    # ---------- 欺诈安全 (22) ----------
    ("m_fraud_hit", "欺诈命中次数", "欺诈", "ds_api_demo", "count", "次", 0, True, "欺诈规则命中次数"),
    ("m_fraud_hit_cust", "欺诈命中客户数", "欺诈", "ds_api_demo", "count", "人", 0, True, "命中欺诈规则的客户数"),
    ("m_fraud_score", "欺诈评分", "欺诈", "ds_api_demo", "avg", "分", 0, True, "欺诈风险评分均值"),
    ("m_device_cnt", "设备指纹数", "欺诈", "ds_behavior", "distinct", "台", 0, True, "设备指纹去重数"),
    ("m_device_risk", "高危设备数", "欺诈", "ds_behavior", "count", "台", 0, True, "标记高危设备数量"),
    ("m_ip_risk_cnt", "风险IP交易笔数", "欺诈", "ds_behavior", "count", "笔", 0, True, "风险IP发起的交易笔数"),
    ("m_geo_abnormal", "异地登录次数", "欺诈", "ds_behavior", "count", "次", 0, True, "与常用地不符的登录"),
    ("m_stolen_cnt", "盗刷交易笔数", "欺诈", "ds_api_demo", "count", "笔", 0, True, "疑似盗刷交易笔数"),
    ("m_cashout_cnt", "套现交易笔数", "欺诈", "ds_behavior", "count", "笔", 0, True, "疑似套现交易笔数"),
    ("m_cashout_amt", "套现交易金额", "欺诈", "ds_behavior", "sum", "元", 0, True, "疑似套现金额"),
    ("m_aml_cnt", "反洗钱预警次数", "欺诈", "ds_sql_demo", "count", "次", 0, True, "可疑洗钱交易预警次数"),
    ("m_aml_amt", "可疑交易金额", "欺诈", "ds_sql_demo", "sum", "元", 0, True, "可疑资金流动金额"),
    ("m_sybil_cnt", "团伙关联客户数", "欺诈", "ds_sql_demo", "count", "人", 0, True, "关联团伙客户数"),
    ("m_wool_cnt", "羊毛党命中次数", "欺诈", "ds_behavior", "count", "次", 0, True, "营销活动套利命中次数"),
    ("m_proxy_ip", "代理IP交易笔数", "欺诈", "ds_behavior", "count", "笔", 0, True, "代理/匿名IP交易笔数"),
    ("m_emu_cnt", "模拟器设备数", "欺诈", "ds_behavior", "count", "台", 0, True, "模拟器环境设备数"),
    ("m_root_cnt", "越狱设备数", "欺诈", "ds_behavior", "count", "台", 0, True, "root/越狱设备数"),
    ("m_batch_open", "批量开户数量", "欺诈", "ds_sql_demo", "count", "户", 0, True, "同设备批量开户数"),
    ("m_cred_stuff", "撞库攻击次数", "欺诈", "ds_sql_demo", "count", "次", 0, True, "撞库登录攻击次数"),
    ("m_phish_cnt", "钓鱼投诉次数", "欺诈", "ds_sql_demo", "count", "次", 0, True, "钓鱼欺诈投诉次数"),
    ("m_open_abn", "开户异常笔数", "欺诈", "ds_sql_demo", "count", "笔", 0, True, "开户信息异常笔数"),
    ("m_txn_abn_amt", "异常交易金额", "欺诈", "ds_behavior", "sum", "元", 0, True, "风控标记异常交易金额"),
    # ---------- 催收处置 (18) ----------
    ("m_collect_cnt", "催收次数", "处置", "ds_alert", "sum", "次", 0, True, "催收联系次数合计"),
    ("m_dispose_rate", "处置率", "处置", "ds_alert", "avg", "%", 2, True, "已处置预警/预警总数"),
    ("m_dispose_cnt", "处置次数", "处置", "ds_alert", "count", "次", 0, True, "预警处置动作次数"),
    ("m_recover_rate", "回款率", "处置", "ds_alert", "avg", "%", 2, True, "催收回款金额/应收金额"),
    ("m_recover_amt", "催收回款金额", "处置", "ds_alert", "sum", "元", 0, True, "催收实际回款金额"),
    ("m_promise_cnt", "承诺还款次数", "处置", "ds_alert", "count", "次", 0, True, "客户承诺还款次数"),
    ("m_promise_keep", "承诺履约率", "处置", "ds_alert", "avg", "%", 2, True, "承诺按期履约比例"),
    ("m_workorder_cnt", "催收工单数", "处置", "ds_alert", "count", "单", 0, True, "催收工单数量"),
    ("m_workorder_overdue", "工单超时数", "处置", "ds_alert", "count", "单", 0, True, "超过SLA未处理工单"),
    ("m_lost_contact", "失联客户数", "处置", "ds_alert", "count", "人", 0, True, "催收失联客户数"),
    ("m_contact_rate", "电话接通率", "处置", "ds_alert", "avg", "%", 2, True, "催收电话接通比例"),
    ("m_outsource", "委外催收金额", "处置", "ds_alert", "sum", "元", 0, True, "委外机构承接金额"),
    ("m_visit_cnt", "上门催收次数", "处置", "ds_alert", "count", "次", 0, True, "上门催收次数"),
    ("m_lawsuit_cnt", "诉讼案件数", "处置", "ds_alert", "count", "件", 0, True, "催收诉讼案件数量"),
    ("m_writeoff_amt", "核销金额", "处置", "ds_alert", "sum", "元", 0, True, "不良贷款核销金额"),
    ("m_writeoff_recover", "核销回收金额", "处置", "ds_alert", "sum", "元", 0, True, "核销后追回金额"),
    ("m_relief_amt", "减免金额", "处置", "ds_alert", "sum", "元", 0, True, "减免本金利息金额"),
    ("m_collect_eff", "有效催收率", "处置", "ds_alert", "avg", "%", 2, True, "有效催收联系/总联系"),
    # ---------- 营销运营 (14) ----------
    ("m_promo_cnt", "促活客户数", "营销", "ds_behavior", "count", "人", 0, True, "促活营销触达客户数"),
    ("m_invite_cnt", "提额邀请数", "营销", "ds_customer", "count", "次", 0, True, "提额邀请发送次数"),
    ("m_cross_sell", "交叉销售数", "营销", "ds_behavior", "count", "次", 0, True, "交叉销售成交次数"),
    ("m_resp_rate", "营销响应率", "营销", "ds_behavior", "avg", "%", 2, True, "营销活动响应比例"),
    ("m_conv_rate", "转化率", "营销", "ds_behavior", "avg", "%", 2, True, "营销线索转化比例"),
    ("m_activate_rate", "激活率", "营销", "ds_behavior", "avg", "%", 2, True, "新客激活比例"),
    ("m_retain_rate", "留存率", "营销", "ds_behavior", "avg", "%", 2, True, "次月留存比例"),
    ("m_rebuy_rate", "复购率", "营销", "ds_behavior", "avg", "%", 2, True, "重复消费比例"),
    ("m_refer_cnt", "推荐客户数", "营销", "ds_customer", "count", "人", 0, True, "老带新推荐客户数"),
    ("m_coupon_use", "优惠券使用数", "营销", "ds_behavior", "count", "张", 0, True, "优惠券核销数量"),
    ("m_activity_join", "活动参与人数", "营销", "ds_behavior", "count", "人", 0, True, "营销活动参与人数"),
    ("m_sleep_wake", "沉睡唤醒数", "营销", "ds_behavior", "count", "人", 0, True, "沉睡客户唤醒数量"),
    ("m_churn_warn", "流失预警客户数", "营销", "ds_behavior", "count", "人", 0, True, "预警流失风险客户数"),
    ("m_churn_save", "流失挽回数", "营销", "ds_behavior", "count", "人", 0, True, "挽回流失客户数量"),
    # ---------- 事件分析 (7) ----------
    ("m_web_stay_7d", "Web 视区停留的过去 7 天总次数", "事件分析", "ds_event", "sum", "次", 0, True, "Web 视区停留事件过去7天总次数"),
    ("m_live_buy_peruser", "直播间-点击立即购买的人均次数", "事件分析", "ds_event", "avg", "次", 2, True, "直播间点击立即购买人均次数"),
    ("m_live_buy_users", "直播间-点击立即购买·用户数", "事件分析", "ds_event", "distinct", "人", 0, True, "直播间点击立即购买去重用户数"),
    ("m_live_buy_total", "直播间-点击立即购买·总次数", "事件分析", "ds_event", "sum", "次", 0, True, "直播间点击立即购买总次数"),
    ("m_custom_idx2", "自定义指标2", "事件分析", "ds_event", "count", "%", 2, True, "直播间点击购买.用户数/总次数 百分比"),
    ("m_page_view", "页面浏览次数", "事件分析", "ds_event", "sum", "次", 0, True, "页面浏览 PV"),
    ("m_btn_click", "按钮点击次数", "事件分析", "ds_event", "sum", "次", 0, True, "关键按钮点击次数"),
    # ---------- 合规监管 (3) ----------
    ("m_car_ratio", "资本充足率", "合规", "ds_sql_demo", "avg", "%", 2, True, "资本充足率监管指标"),
    ("m_provision", "拨备覆盖率", "合规", "ds_sql_demo", "avg", "%", 2, True, "拨备覆盖率监管指标"),
    ("m_leverage", "杠杆率", "合规", "ds_sql_demo", "avg", "%", 2, True, "杠杆率监管指标"),
    # ---------- 补充 19 个（凑满 200，不与现有重复） ----------
    ("m_age_lt25", "25岁以下客户数", "客群", "ds_customer", "count", "人", 0, True, "年龄<25岁的在贷客户数"),
    ("m_age_50p", "50岁以上客户数", "客群", "ds_customer", "count", "人", 0, True, "年龄≥50岁的在贷客户数"),
    ("m_local_cust", "本地户籍客户数", "客群", "ds_customer", "count", "人", 0, True, "户籍地与常驻地一致的客户数"),
    ("m_credit_fixed", "固定授信额度", "授信", "ds_customer", "sum", "元", 0, True, "固定额度授信总额"),
    ("m_credit_self", "自助提额次数", "授信", "ds_customer", "count", "次", 0, True, "客户自助申请提额次数"),
    ("m_credit_reval", "额度重估次数", "授信", "ds_customer", "count", "次", 0, True, "系统额度重估次数"),
    ("m_loan_settle", "当月结清贷款", "贷款", "ds_loan", "count", "笔", 0, True, "当月正常结清贷款笔数"),
    ("m_loan_migrate", "贷款迁徙率", "贷款", "ds_loan", "avg", "%", 2, True, "M0→M1迁徙比例"),
    ("m_loan_util_days", "贷款使用天数", "贷款", "ds_loan", "avg", "天", 0, True, "贷款平均实际使用天数"),
    ("m_first_overdue", "首逾率", "风险", "ds_loan", "avg", "%", 2, True, "新发放贷款首次逾期比例"),
    ("m_three_six", "连三累六客户数", "风险", "ds_loan", "count", "人", 0, True, "连续3次/累计6次逾期客户"),
    ("m_sleep_cust", "睡眠客户占比", "风险", "ds_behavior", "avg", "%", 2, True, "30天无交易客户占比"),
    ("m_night_txn", "夜间消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "22:00-06:00消费金额"),
    ("m_offsite_txn", "异地消费金额", "行为", "ds_behavior", "sum", "元", 0, True, "非常驻地消费金额"),
    ("m_fake_info", "虚假资料申请数", "欺诈", "ds_sql_demo", "count", "笔", 0, True, "申请资料造假笔数"),
    ("m_collect_complaint", "催收投诉次数", "处置", "ds_alert", "count", "次", 0, True, "催收相关客户投诉次数"),
    ("m_pay_intent", "还款意愿评分", "处置", "ds_alert", "avg", "分", 0, True, "客户还款意愿评分均值"),
    ("m_click_rate", "按钮点击率", "事件分析", "ds_event", "avg", "%", 2, True, "按钮点击/曝光比例"),
    ("m_stay_dur", "平均停留时长", "事件分析", "ds_event", "avg", "秒", 0, True, "页面平均停留时长"),
]

# 保留现有 24 个（读磁盘 midMetrics.json，若存在）
import json, os
keep = []
if os.path.exists('midMetrics.json'):
    keep = json.load(open('midMetrics.json', encoding='utf-8'))
else:
    keep = []  # 由脚本调用方兜底

# 合并去重（新指标 id 不与现有冲突）
existing = {m['id'] for m in keep}
extra_ts = []
for it in EXTRA:
    mid, name, group, ds, agg, unit, prec, enabled, desc = it[:9]
    viz = it[9] if len(it) > 9 else None
    if mid in existing:
        continue
    base = f"    {{ id: '{mid}', name: '{name}', group: '{group}', desc: '{desc}', dataSourceId: '{ds}', type: 'base', field: '{mid[2:]}', agg: '{agg}', unit: '{unit}', precision: {prec}, enabled: {str(enabled).lower()}"
    viz_s = f", vizType: '{viz}'" if viz else ""
    extra_ts.append(base + viz_s + " },")

print("existing:", len(keep), "| new:", len(extra_ts), "| total:", len(keep) + len(extra_ts))
with open('/tmp/metrics_extra.ts.txt', 'w', encoding='utf-8') as f:
    f.write("\n".join(extra_ts))
print("written /tmp/metrics_extra.ts.txt")
